# Generated by Django 5.1.1 on 2024-10-27 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spravApp.fam')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spravApp.name')),
                ('otc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spravApp.otc')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='spravApp.street')),
            ],
        ),
    ]
