# Generated by Django 5.1.1 on 2024-10-27 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravApp', '0003_mainitem_appr_mainitem_bldn_mainitem_bldn_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='fam',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='spravApp.fam'),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='spravApp.name'),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='otc',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='spravApp.otc'),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='street',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='spravApp.street'),
        ),
    ]
