# Generated by Django 5.1.1 on 2024-10-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravApp', '0010_remove_mainitem_tel_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fam',
            name='val',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='name',
            name='val',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='otc',
            name='val',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='street',
            name='val',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Улица'),
        ),
    ]
