# Generated by Django 5.1.1 on 2024-10-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spravApp', '0008_remove_mainitem_tel_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainitem',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.DeleteModel(
            name='Phones',
        ),
    ]
